{
    "openapi": "3.0.0",
    "info": {
        "title": "API documentation SPN",
        "description": "Ikhwan Computer",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "email": "afd.zik@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "1.0.0"
    },
    "paths": {
        "/spnbackend/public/api/login": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "",
                "operationId": "id",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "email": "admin@admin.com",
                                    "password": "********"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/spnbackend/public/api/logout": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "",
                "operationId": "id",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/spnbackend/public/api/jabatan/list": {
            "get": {
                "tags": [
                    "Jabatan"
                ],
                "summary": "List Jabatan",
                "description": "List Jabatan",
                "operationId": "auth",
                "responses": {
                    "default": {
                        "description": "successful operation"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/spnbackend/public/api/jabatan/view": {
            "get": {
                "tags": [
                    "Jabatan"
                ],
                "summary": "Detail Jabatan",
                "description": "Jabatan By ID",
                "operationId": "auth",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": false,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "default": {
                        "description": "successful operation"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/spnbackend/public/api/jabatan/save": {
            "post": {
                "tags": [
                    "Jabatan"
                ],
                "summary": "Tambah atau edit Jabatan",
                "description": "Tambah atau edit Jabatan",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": false,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "group_name": {
                                        "type": "string"
                                    },
                                    "group_code": {
                                        "type": "string"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "group_name": "Ikhwan Komputer",
                                    "group_code": "IKE"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/spnbackend/public/api/jabatan/delete": {
            "post": {
                "tags": [
                    "Jabatan"
                ],
                "summary": "Hapus Jabatan",
                "description": "Hapus Jabatan",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/spnbackend/public/api/user/list": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "List User",
                "description": "List User",
                "operationId": "auth",
                "parameters": [
                    {
                        "name": "skip",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "name": "take",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "default": {
                        "description": "successful operation"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/spnbackend/public/api/user/view": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "Detail User",
                "description": "User By ID",
                "operationId": "auth",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": false,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "default": {
                        "description": "successful operation"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/spnbackend/public/api/user/save": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "Tambah atau edit User",
                "description": "Tambah atau edit User",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": false,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "username": {
                                        "type": "string"
                                    },
                                    "full_name": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    },
                                    "phone": {
                                        "type": "string"
                                    },
                                    "address": {
                                        "type": "string"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "username": "Simba",
                                    "full_name": "Simba The Cat",
                                    "email": "simba@thecat.dev.id",
                                    "password": "*****",
                                    "phone": "084212312",
                                    "address": "Jl. Ridwan Rais Depok, Jawa Barat"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/spnbackend/public/api/user/changePassword": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "Ubah Password User",
                "description": "Ubah Password User dari ID",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": false,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "password": {
                                        "type": "string"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "password": "*****"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/spnbackend/public/api/user/delete": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "Hapus User",
                "description": "Hapus User",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/spnbackend/public/api/menu/list": {
            "get": {
                "tags": [
                    "Menu"
                ],
                "summary": "List Menu",
                "description": "List Menu",
                "operationId": "auth",
                "responses": {
                    "default": {
                        "description": "successful operation"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/spnbackend/public/api/Menu/view": {
            "get": {
                "tags": [
                    "Menu"
                ],
                "summary": "Detail Menu",
                "description": "Menu By ID",
                "operationId": "auth",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": false,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "default": {
                        "description": "successful operation"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/spnbackend/public/api/Menu/sidebar": {
            "get": {
                "tags": [
                    "Menu"
                ],
                "summary": "Sidebar Nav",
                "description": "Menu Sidebar",
                "operationId": "auth",
                "responses": {
                    "default": {
                        "description": "successful operation"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/spnbackend/public/api/menu/save": {
            "post": {
                "tags": [
                    "Menu"
                ],
                "summary": "Tambah atau edit Menu",
                "description": "Tambah atau edit Menu",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": false,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "menu_name": {
                                        "type": "string"
                                    },
                                    "display": {
                                        "type": "string"
                                    },
                                    "url": {
                                        "type": "string"
                                    },
                                    "icon": {
                                        "type": "string"
                                    },
                                    "isparent": {
                                        "type": "boolean"
                                    },
                                    "parent_id": {
                                        "type": "string"
                                    },
                                    "index": {
                                        "type": "integer"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "menu_name": "menu",
                                    "display": "Menu",
                                    "url": "/Menu",
                                    "icon": "fa-menu",
                                    "isparent": true,
                                    "parent_id": null,
                                    "index": 1
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/spnbackend/public/api/menu/delete": {
            "post": {
                "tags": [
                    "Menu"
                ],
                "summary": "Hapus Menu",
                "description": "Hapus Menu",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/spnbackend/public/api/suratKeluar/save": {
            "post": {
                "tags": [
                    "Surat Keluar"
                ],
                "summary": "Tambah atau edit Surat Keluar",
                "description": "Tambah atau edit Surat Keluar",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Project id",
                        "required": false,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "jenis_surat": {
                                        "type": "string"
                                    },
                                    "klasifikasi_surat": {
                                        "type": "string"
                                    },
                                    "sifat_surat": {
                                        "type": "string"
                                    },
                                    "tujuan_surat": {
                                        "type": "string"
                                    },
                                    "hal_surat": {
                                        "type": "string"
                                    },
                                    "lampiran_surat": {
                                        "type": "string"
                                    },
                                    "approval_user": {
                                        "type": "integer"
                                    },
                                    "to_user": {
                                        "type": "integer"
                                    },
                                    "file": {
                                        "type": "file"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "jenis_surat": "Penting",
                                    "klasifikasi_surat": "IT",
                                    "sifat_surat": "Segera",
                                    "tujuan_surat": "Ikhwan Komputer",
                                    "hal_surat": "-",
                                    "lampiran_surat": "-",
                                    "approval_user": 1,
                                    "to_user": 2,
                                    "file": "file"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/spnbackend/public/api/suratKeluar/disposisi": {
            "post": {
                "tags": [
                    "Surat Keluar"
                ],
                "summary": "Tambah atau edit Surat Keluar",
                "description": "Tambah atau edit Surat Keluar",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "surat_keluar_id": {
                                        "type": "integer"
                                    },
                                    "tujuan_user": {
                                        "type": "integer"
                                    },
                                    "file_id": {
                                        "type": "file"
                                    },
                                    "keterangan": {
                                        "type": "string"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "surat_keluar_id": "3",
                                    "tujuan_user": "1",
                                    "file_id": "[]",
                                    "keterangan": "Mohon Respon"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/spnbackend/public/api/suratKeluar/read": {
            "post": {
                "tags": [
                    "Surat Keluar"
                ],
                "summary": "Ubah status baca disposisi",
                "description": "ubah Status Baca Disposisi",
                "parameters": [
                    {
                        "name": "idDisposisi",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "components": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "bearerFormat": "JWT",
                "scheme": "bearer"
            }
        }
    },
    "tags": [
        {
            "name": "Sistem SPN",
            "description": "Ikhwan Komputer"
        }
    ]
}